<?php

namespace Autopoets\NewsBundle\Entity;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
	{
		return $this->findBy([], ['created_at' => 'DESC']);
	}

	public function findLimited($limit) 
	{
		return $this->createQueryBuilder('u')
			->setMaxResults($limit)
			->orderBy('u.created_at', 'DESC')
			->getQuery()
			->execute();
	}
}
